locale = "ro"
label = "Română"
direction = "ltr"
weight = 4

title = "Ivan Luminaria"

[params]
  dateFormat = "2 January 2006"
  description = "Ivan Luminaria, Technical Leader pentru baze de date și Data Warehouse mission-critical: Oracle, PostgreSQL, MySQL. Blog Database Strategy, 30 de ani în IT."