locale = "es"
label = "Español"
direction = "ltr"
weight = 3

title = "Ivan Luminaria"

[params]
  dateFormat = "2 January 2006"
  description = "Ivan Luminaria, Technical Leader para bases de datos y Data Warehouse mission-critical: Oracle, PostgreSQL, MySQL. Blog Database Strategy, 30 años de IT."