locale = "ro"
label = "Română"
direction = "ltr"
weight = 4

title = "Ivan Luminaria"

[params]
  dateFormat = "2 January 2006"
  description = "Ivan Luminaria, Technical Leader pentru baze de date critice Oracle, PostgreSQL și MySQL. Blog Database Strategy cu cazuri reale din 30 de ani de IT."